// Generates the shared cross-implementation fixtures from Fixtures/kitchen-sink.json:
//   Tests/ADFBeamTests/Fixtures/kitchen-sink.chunks.txt — one frame payload per line
//   Tools/adf-beam-extension/test-fixture.js            — fixture JSON for test.html
//   node Tools/adf-beam-extension/make-fixture.mjs
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const protocol = require('./shared/protocol.js');

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const json = readFileSync(join(root, 'Fixtures', 'kitchen-sink.json'), 'utf8');

const frames = protocol.encodeFrames(json, 'kitchen-sink-fixture');
const outDir = join(root, 'Tests', 'ADFBeamTests', 'Fixtures');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'kitchen-sink.chunks.txt'), frames.join('\n') + '\n');
console.log(`wrote ${frames.length} frames to Tests/ADFBeamTests/Fixtures/kitchen-sink.chunks.txt`);

writeFileSync(
  join(here, 'test-fixture.js'),
  `// Generated by make-fixture.mjs — do not edit.\nconst ADF_BEAM_TEST_FIXTURE = ${JSON.stringify(json)};\n`,
);
console.log('wrote Tools/adf-beam-extension/test-fixture.js');
